
name: Pull Request Workflow
on: 
  pull_request:
    branch:
      main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.0"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for demo Python project  
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Testing the project using pytest
        run: |
          pip install coverage
          cd tests/functionalTestCases/src
          coverage run -m pytest -v tests.py && coverage report -m
      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v1.4.3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for submitting this pull request! :tada:
            
            We'll review it as soon as possible and get back to you with any feedback.
